# Generated by Django 5.2 on 2026-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_trainer_links_and_plan_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='workout_type',
            field=models.CharField(blank=True, choices=[('strength', 'Сила'), ('cardio', 'Кардио'), ('flexibility', 'Гибкость'), ('circuit', 'Круговая')], default='strength', max_length=20, verbose_name='Тип тренировки'),
        ),
    ]
