# Generated by Django 5.2 on 2026-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_trainingplan_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='default_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность по умолчанию, мин'),
        ),
    ]
