# Generated by Django 5.2 on 2026-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_rename_default_duration_to_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='workout_type',
            field=models.CharField(blank=True, choices=[('strength', 'Сила'), ('cardio', 'Кардио'), ('flexibility', 'Гибкость'), ('circuit', 'Круговая'), ('other', 'Другое')], default='strength', max_length=20, verbose_name='Тип тренировки'),
        ),
    ]
