from trainings.models import ExerciseCategory

EXERCISES: list[tuple[str, str, str]] = [
    ('Жим лёжа', ExerciseCategory.STRENGTH, 'Базовое жимовое для груди, трицепса и передних дельт.'),
    ('Жим лёжа гантелей', ExerciseCategory.STRENGTH, 'Жим гантелей лёжа на горизонтальной скамье.'),
    ('Жим в наклоне', ExerciseCategory.STRENGTH, 'Жим штанги на наклонной скамье для верха груди.'),
    ('Отжимания от пола', ExerciseCategory.STRENGTH, 'Жимовое с собственным весом.'),
    ('Отжимания на брусьях', ExerciseCategory.STRENGTH, 'Жим на параллельных брусьях, акцент на грудь и трицепс.'),
    ('Жим гантелей сидя', ExerciseCategory.STRENGTH, 'Жим гантелей сидя для плеч.'),
    ('Жим стоя', ExerciseCategory.STRENGTH, 'Армейский жим штанги стоя.'),
    ('Жим в Смите', ExerciseCategory.STRENGTH, 'Жим в тренажёре Смита.'),
    ('Махи гантелей в стороны', ExerciseCategory.STRENGTH, 'Изоляция средних дельт.'),
    ('Махи в наклоне', ExerciseCategory.STRENGTH, 'Разведение гантелей в наклоне для задних дельт.'),
    ('Разводка гантелей лёжа', ExerciseCategory.STRENGTH, 'Изоляция грудных мышц.'),
    ('Присед со штангой', ExerciseCategory.STRENGTH, 'Базовый присед со штангой на спине.'),
    ('Фронтальный присед', ExerciseCategory.STRENGTH, 'Присед со штангой на груди.'),
    ('Присед в Смите', ExerciseCategory.STRENGTH, 'Присед в тренажёре Смита.'),
    ('Жим ногами', ExerciseCategory.STRENGTH, 'Жим платформы в тренажёре.'),
    ('Выпады с гантелями', ExerciseCategory.STRENGTH, 'Выпады вперёд с гантелями.'),
    ('Болгарские выпады', ExerciseCategory.STRENGTH, 'Выпады с задней ногой на скамье.'),
    ('Румынская тяга', ExerciseCategory.STRENGTH, 'Тяга на прямых ногах для бицепса бедра.'),
    ('Становая тяга', ExerciseCategory.STRENGTH, 'Классическая становая со штангой.'),
    ('Становая сумо', ExerciseCategory.STRENGTH, 'Становая с широкой постановкой ног.'),
    ('Ягодичный мост', ExerciseCategory.STRENGTH, 'Мост со штангой или собственным весом.'),
    ('Подъём на носки стоя', ExerciseCategory.STRENGTH, 'Икроножные в тренажёре или со штангой.'),
    ('Сгибание ног лёжа', ExerciseCategory.STRENGTH, 'Изоляция бицепса бедра в тренажёре.'),
    ('Разгибание ног', ExerciseCategory.STRENGTH, 'Изоляция квадрицепса в тренажёре.'),
    ('Подтягивания', ExerciseCategory.STRENGTH, 'Вертикальная тяга с собственным весом.'),
    ('Подтягивания обратным хватом', ExerciseCategory.STRENGTH, 'Подтягивания с акцентом на бицепс.'),
    ('Тяга верхнего блока', ExerciseCategory.STRENGTH, 'Вертикальная тяга в кроссовере.'),
    ('Тяга нижнего блока', ExerciseCategory.STRENGTH, 'Горизонтальная тяга сидя в кроссовере.'),
    ('Тяга штанги в наклоне', ExerciseCategory.STRENGTH, 'Тяга штанги к поясу в наклоне.'),
    ('Тяга Т-грифа', ExerciseCategory.STRENGTH, 'Тяга в тренажёре с Т-образным грифом.'),
    ('Тяга гантели в наклоне', ExerciseCategory.STRENGTH, 'Односторонняя тяга гантели к поясу.'),
    ('Подъём штанги на бицепс', ExerciseCategory.STRENGTH, 'Классическое сгибание рук со штангой.'),
    ('Молотковые сгибания', ExerciseCategory.STRENGTH, 'Сгибания с нейтральным хватом гантелей.'),
    ('Французский жим', ExerciseCategory.STRENGTH, 'Разгибание на трицепс лёжа со штангой.'),
    ('Разгибание на блоке', ExerciseCategory.STRENGTH, 'Трицепс на верхнем блоке.'),
    ('Гиперэкстензия', ExerciseCategory.STRENGTH, 'Разгибание спины на скамье.'),
    ('Скручивания', ExerciseCategory.STRENGTH, 'Пресс: подъём корпуса лёжа.'),
    ('Подъём ног в висе', ExerciseCategory.STRENGTH, 'Пресс и сгибатели бедра в висе.'),
    ('Бёрпи', ExerciseCategory.MIXED, 'Комплекс: присед, планка, отжимание, прыжок.'),
    ('Беговая дорожка', ExerciseCategory.CARDIO, 'Бег или ходьба на беговой дорожке.'),
    ('Эллипс', ExerciseCategory.CARDIO, 'Кардио на эллиптическом тренажёре.'),
    ('Велоэргометр', ExerciseCategory.CARDIO, 'Велотренажёр в зале.'),
    ('Скакалка', ExerciseCategory.CARDIO, 'Интервалы или непрерывная работа со скакалкой.'),
    ('Гребной тренажёр', ExerciseCategory.CARDIO, 'Кардио на гребном тренажёре.'),
    ('Степпер', ExerciseCategory.CARDIO, 'Кардио на степпере.'),
    ('Бег на улице', ExerciseCategory.CARDIO, 'Лёгкий или темповый бег.'),
    ('Велосипед', ExerciseCategory.CARDIO, 'Катание на велосипеде.'),
    ('Плавание', ExerciseCategory.CARDIO, 'Плавание в бассейне.'),
    ('Планка', ExerciseCategory.MOBILITY, 'Статическое удержание корпуса.'),
    ('Боковая планка', ExerciseCategory.MOBILITY, 'Планка на боку для косых мышц.'),
    ('Растяжка спины', ExerciseCategory.MOBILITY, 'Мягкая растяжка мышц спины.'),
    ('Кошка-корова', ExerciseCategory.MOBILITY, 'Мобильность грудного и поясничного отдела.'),
    ('Выпад с растяжкой', ExerciseCategory.MOBILITY, 'Выпад с удержанием для бёдер и паха.'),
    ('Растяжка бёдер', ExerciseCategory.MOBILITY, 'Растяжка сгибателей бедра.'),
    ('Йога-треугольник', ExerciseCategory.MOBILITY, 'Поза треугольника для боковой линии тела.'),
    ('Скручивание лёжа с фиксацией', ExerciseCategory.MOBILITY, 'Мягкое скручивание для грудного отдела.'),
    ('Круговая тренировка', ExerciseCategory.MIXED, 'Станции подряд без длительного отдыха.'),
    ('Функциональный круг', ExerciseCategory.MIXED, 'Круг из силовых и кардио-элементов.'),
    ('Канат', ExerciseCategory.MIXED, 'Работа с боевым канатом.'),
    ('Медбол — броски', ExerciseCategory.MIXED, 'Броски медбола в стену или на пол.'),
    ('Кettlebell свинг', ExerciseCategory.MIXED, 'Махи гирей для задней цепи и кардио.'),
]
