# Generated by Django 5.2 on 2026-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_bodymetric_plan_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='workout_type',
            field=models.CharField(choices=[('strength', 'Сила'), ('cardio', 'Кардио'), ('flexibility', 'Гибкость'), ('circuit', 'Круговая'), ('other', 'Другое')], default='strength', max_length=20, verbose_name='Тип тренировки'),
        ),
    ]
